title: Slate theme
description: Slate is a theme for GitHub Pages.
show_downloads: false
google_analytics:
theme: jekyll-theme-slate

remote_theme: pages-themes/slate@v0.2.0

title: Dr. Alexandra Fedorets
description: Expert on Digitalization and Data Analysis | Empirical Labor Economist
